--- 
addons: ~
after_script: 
  - "ssh -i ./deploy_key {SERVER_USER}@{SERVER_IP} cd /var/www/travis-ci-article && git pull origin master"
before_install: 
  - "openssl aes-256-cbc -K $encrypted_189e52c2c347_key -iv $encrypted_189e52c2c347_iv -in deploy_key.enc -out deploy_key -d"
  - "eval \"$(ssh-agent -s)\""
  - "chmod 600 deploy_key"
  - "echo -e \"Host {SERVER_IP}\\n\\tStrictHostKeyChecking no\\n\" >> ~/.ssh/config"
  - "ssh-add deploy_key"
before_script: 
  - "python init_db.py"
branches: 
  only: 
    - master
language: python
python: 
  - "3.9.2"
services: "-sqlite3"
ssh_known_hosts: 
  - 
    SERVER_IP: ~
language: python
python:
	- 3.9.2
services:
	-sqlite3
before_script:
	- python init_db.py
addons:
	ssh_known_hosts:
	- {SERVER_IP}
branches:
   only:
   - master

before_install:
- openssl aes-256-cbc -K $encrypted_189e52c2c347_key -iv $encrypted_189e52c2c347_iv
  -in deploy_key.enc -out deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_key
- echo -e "Host {SERVER_IP}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add deploy_key

after_script:
  - ssh -i ./deploy_key {SERVER_USER}@{SERVER_IP} cd /var/www/travis-ci-article && git pull origin master

